language: node_js
node_js:
    - "0.10"
services:
  - xvfb
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export CHROME_BIN=google-chrome
    - export DISPLAY=:99.0
before_script:
    - npm install
